### PR TITLE
Just store pk in json

### PR DESCRIPTION
**Pull request by simplicbe**

### CODE REVIEW

**Comment by simplicbe** [comment]
In the current sample this reduce the file size up to 90% and the speed improvement is about 70%-80%.

**Comment by yvz5** [comment]
and if you compress this json file ? I would be really interested in results

**Comment by simplicbe** [comment]
@yvz5 we could make compression optional. Would be easy.

**Comment by simplicbe** [comment]
@yvz5 https://github.com/simplic/simplic-tablemonitor/issues/5

**Pull request merged**
